### Pandas-DataFrame and Series
Pandas is a powerfull data manipulation library in python. Widely used for data analysis and data cleaning. It provides two primary data structures: Series and dataframe. A series is a one-dimentional array-like object, while a dataframe is a two-dimentional, size-mutable and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [50]:
import pandas as pd

In [51]:
# Series
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print("Series\n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [52]:
# Create a series from dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [53]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [54]:
# Dataframe
# Create a Dataframe from a dictionary of list

data = {
    'Name': ["Trupti", "Shweta", "Mayuri"],
    "Age": [21, 22, 18],
    "City": ["Pune", "Nagpur", "Gadchiroli"]
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age        City
0  Trupti   21        Pune
1  Shweta   22      Nagpur
2  Mayuri   18  Gadchiroli
<class 'pandas.DataFrame'>

In [55]:
# Create a Datafrme from list of dictionaries

data = [
    {"Name": "Trupti", "Age": 21, "City": "Pune"},
    {"Name": "Shweta", "Age": 22, "City": "Nagpur"},
    {"Name": "Mayuri", "Age": 18, "City": "Gadchiroli"},
    {"Name": "John", "Age": 30, "City": "Florida"},
]

df = pd.DataFrame(data)
print(df)

     Name  Age        City
0  Trupti   21        Pune
1  Shweta   22      Nagpur
2  Mayuri   18  Gadchiroli
3    John   30     Florida

In [56]:
df2 = pd.read_csv("sales_data.csv")
df2.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [57]:
# Accessing data from Dataframe
df

     Name  Age        City
0  Trupti   21        Pune
1  Shweta   22      Nagpur
2  Mayuri   18  Gadchiroli
3    John   30     Florida

In [58]:
df['Name']

0    Trupti
1    Shweta
2    Mayuri
3      John
Name: Name, dtype: str

In [59]:
df.loc[0] # location

Name    Trupti
Age         21
City      Pune
Name: 0, dtype: object

In [60]:
df.iloc[2] # index location

Name        Mayuri
Age             18
City    Gadchiroli
Name: 2, dtype: object

In [61]:
# Acessing a specified element
df.at[1, "Age"]

np.int64(22)

In [62]:
df.at[1, "Name"]

'Shweta'

In [63]:
# Acessing a specified element using iat
df.iat[0, 2]

'Pune'

In [64]:
# Data manipulation with Dataframes
df

     Name  Age        City
0  Trupti   21        Pune
1  Shweta   22      Nagpur
2  Mayuri   18  Gadchiroli
3    John   30     Florida

In [65]:
df['Salary'] = [50000, 60000, 70000, 80000]
df

     Name  Age        City  Salary
0  Trupti   21        Pune   50000
1  Shweta   22      Nagpur   60000
2  Mayuri   18  Gadchiroli   70000
3    John   30     Florida   80000

In [66]:
# Remove a column
df.drop("Salary", axis=1, inplace=True) # inplace = True mean do it permanantly

In [67]:
df

     Name  Age        City
0  Trupti   21        Pune
1  Shweta   22      Nagpur
2  Mayuri   18  Gadchiroli
3    John   30     Florida

In [68]:
# Add age to the column
df['Age'] = df['Age'] + 1
df

     Name  Age        City
0  Trupti   22        Pune
1  Shweta   23      Nagpur
2  Mayuri   19  Gadchiroli
3    John   31     Florida

In [69]:
df.drop(3, inplace=True)
df

     Name  Age        City
0  Trupti   22        Pune
1  Shweta   23      Nagpur
2  Mayuri   19  Gadchiroli

In [72]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [74]:
df2.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000